# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Restore
        run: nuget restore LottoApp.sln
      - name: Build
        run: msbuild LottoApp.sln
      - name: CheckBuild
        run: ls LottoApp/ -R

